[build]
  base = "/"
  command = "pnpm --filter web prepare && pnpm --filter web build"
  publish = "apps/web/dist"
  functions = "apps/web/.netlify/functions-internal"

[build.environment]
  # Crucial for Nuxt + pnpm on Netlify
  PNPM_FLAGS = "--shamefully-hoist"
  # Set the Node version to match your local environment
  NODE_VERSION = "20" 