[build]
  base = "/"
  command = "pnpm build"
  publish = "apps/web/.output/public"
  functions = "apps/web/.output/server"

[build.environment]
  # Crucial for Nuxt + pnpm on Netlify
  PNPM_FLAGS = "--shamefully-hoist"
  # Set the Node version to match your local environment
  NODE_VERSION = "20" 